# Generated by Django 2.0.6 on 2018-08-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
