# Generated by Django 2.0.6 on 2018-08-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_actionbtn_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionbtn',
            old_name='title',
            new_name='action_title',
        ),
        migrations.AlterField(
            model_name='homechoose',
            name='describe',
            field=models.TextField(max_length=230),
        ),
        migrations.AlterField(
            model_name='homeservice',
            name='describe',
            field=models.TextField(max_length=430),
        ),
    ]
