# Generated by Django 2.0.6 on 2018-08-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20180803_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionbtn',
            name='action_title',
            field=models.CharField(max_length=100),
        ),
    ]
