# Generated by Django 2.0.6 on 2018-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
