# Generated by Django 2.0.6 on 2018-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_aboutbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('describe', models.TextField(max_length=400)),
            ],
        ),
    ]
