# Generated by Django 2.0.6 on 2018-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_servicebanner_servicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
