# Generated by Django 2.0.6 on 2018-08-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_contactbanner_officeaddress_officenumber_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('work', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDimenssion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('area', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InnerFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='')),
                ('about_project', models.TextField()),
            ],
        ),
    ]
