# Generated by Django 2.1 on 2018-08-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0019_auto_20180819_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerfeature',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webpage.FeatureName'),
            preserve_default=False,
        ),
    ]
