# Generated by Django 2.1 on 2018-08-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_innerfeature_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innerfeature',
            old_name='title',
            new_name='head',
        ),
    ]
