# Generated by Django 2.1 on 2018-08-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0021_auto_20180820_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innerfeature',
            old_name='head',
            new_name='house_name',
        ),
    ]
