# Generated by Django 2.1 on 2018-08-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0022_auto_20180820_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerfeature',
            name='house_name',
        ),
    ]
