# Generated by Django 2.1 on 2018-08-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0023_remove_innerfeature_house_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InnerFeature',
        ),
    ]
