# Generated by Django 2.1 on 2018-08-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_delete_innerfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=400)),
                ('author1', models.CharField(max_length=60)),
                ('position1', models.CharField(blank=True, max_length=60)),
                ('author2', models.CharField(max_length=60)),
                ('position2', models.CharField(blank=True, max_length=60)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.FeatureName')),
            ],
        ),
    ]
