# Generated by Django 2.1 on 2018-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_innerfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerfeature',
            name='slide1',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innerfeature',
            name='slide2',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innerfeature',
            name='slide3',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
